---
version: '2'
services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
        expose:
            - 2181

    kafka:
        image: wurstmeister/kafka
        expose:
            - 9092
        depends_on:
            - zookeeper
        links:
            - zookeeper:zk
        environment:
            HOSTNAME_COMMAND: "ifconfig  eth0 | \
                               egrep -o 'inet addr:[0-9.]*' | \
                                cut -d: -f2 | tr -d ' '"
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_AUTO_CREATE_TOPIC_ENABLE: 'true'
            KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    notebook:
        image: juanito/docker-stacks
        expose:
            - 8888
        ports:
            - 8888:8888
        links:
            - kafka
            - zookeeper:zk
        volumes:
            - ./notebooks:/home/jovyan/work/
